---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-api-server-deploy
  labels:
    app: api-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: google-api-server
        image: 'localhost:5000/google-api-server:latest'
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: google-api-server-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: api-server-service
                port:
                  number: 3000
---
